services:

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: projectr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      SECRET_KEY: 'change-this-to-a-secret-key'
      POSTGRES_DB: projectr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: