# Generated by Django 5.1.2 on 2024-10-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name_plural": "cities"},
        ),
        migrations.AddField(
            model_name="project",
            name="idx",
            field=models.IntegerField(default=1),
        ),
    ]
