# Generated by Django 5.1.2 on 2024-10-11 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_calculated_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state')},
        ),
    ]
